### ISSUE TITLE
Hanging once disconnect touched

### ISSUE THREAD

**Issue by WilledgeR** [hiddify/old.hiddify.com#7]
Im using latest version of the sofware for windows.

When I click on disconnect button the software will never respond. 

Also the network access of the other apps like chome will get affected.

**Comment by WilledgeR** [comment]
I tried to close the app via Task manager? is the any log option to inspect whats going on?

[Im using prebuilt version]

**Comment by lymanjre** [comment]
It s not related to this repo. Pls open an issue on Hiddify Next repo
